default.xml: lock in revision for meta-browser and meta-clang
Otherwise the HEAD of master on meta-clang throws error:

ERROR: Layer clang-layer is not compatible with the core layer which
only supports these series: kirkstone (layer is compatible with
mickledore)

Therefore, we need to bump meta-browser back to a compatible version
that builds with this version of meta-clang (chromium version
101.0.4951.54)

Also remove unneeded meta-rust layer.

Signed-off-by: Chris Dimich <chris.dimich@boundarydevices.com>